function[V,O,OS,Psi_soil,Psi_s_H,Psi_s_L,Exwat_H,Exwat_L,Ko]=...
	SoilMoistureConductivityUpdate(V,Pcla,Psan,Porg,Kfc,Phy,SPAR,Kbot,...
	CASE_ROOT_H,CASE_ROOT_L,ZR95_H,ZR95_L,ZR50_H,ZR50_L,ZRmax_H,ZRmax_L,Zs,...
	Rrootl_H,Rrootl_L,PsiL50_H,PsiL50_L,PsiX50_H,PsiX50_L)

% Calculate soil parameters depending on soil composition
[Zs,dz,ms,Osat,Ohy,nVG,alpVG,Ks_Zs,L,Pe,O33,SPAR,EvL_Zs,Inf_Zs,...
	RfH_Zs,RfL_Zs,~,Kbot,Slo_pot,Dz,aR,aTop,~,~,~,~]...
	=soil_functions.SoilParametersTotal(Pcla,Psan,Porg,Kfc,Phy,SPAR,Kbot,...
	CASE_ROOT_H,CASE_ROOT_L,ZR95_H,ZR95_L,ZR50_H,ZR50_L,ZRmax_H,ZRmax_L,Zs);

% Update soil moisture content in different soil layers.
[O,ZWT,OF,OS,Psi_s_H,Psi_s_L,gsr_H,gsr_L,Exwat_H,Exwat_L,Rd,WTR,POT,OH,OL]...
	=soil_functions.Soil_Water_MultiLayer(V,Zs,dz,ms,...
	Osat,Ohy,nVG,alpVG,Ks_Zs,L,Pe,O33,SPAR,EvL_Zs,Inf_Zs,...
	RfH_Zs,RfL_Zs,Rrootl_H,Rrootl_L,PsiL50_H,PsiL50_L,PsiX50_H,PsiX50_L);

% Calculate hydraulic conductivity and soil water potential
for i=1:length(O)
[Ko(i),Psi_soil(i)]=soil_functions.Conductivity_Suction...
	(SPAR,Ks_Zs(i),Osat(i),Ohy(i),L(i),Pe(i),O33(i),alpVG(i),nVG(i),O(i));
end

